disabled_rules:
  - line_length
  - type_name
  - trailing_comma

opt_in_rules:
  - file_header
  - sorted_imports

excluded:
  - .build
  - Modules/.build
  - Modules/Package.swift

identifier_name:
  min_length: 2
