name: 'Setup JDK'

inputs:
  java-version:
    description: "Java version. Just for DRY inside of this file."
    default: "17"

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b # v1.0.6

    - name: Copy CI gradle.properties
      shell: bash
      run: |
        mkdir -p ~/.gradle
        cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: temurin
        java-version: ${{ inputs.java-version }}

    # Better than caching and/or extensions of actions/setup-java
    - name: Setup Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629 # v2.4.2
      with:
        gradle-version: wrapper
