name: Format

on:
  pull_request:

run-name: "Format by ${{ github.actor }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - uses: ./.github/actions/setup-java
      - name: Check spotless
        run: ./gradlew spotlessCheck --stacktrace
