name: UnitTest

on:
  push:
    branches:
      - main
  pull_request:

run-name: "UnitTest by ${{ github.actor }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - uses: ./.github/actions/setup-java

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace

      - id: test-reports
        name: Aggregate reports directory into the single directory
        if: always()
        run: |
          echo "path=.test-reports" >> $GITHUB_OUTPUT

          mkdir -p .test-reports

          while read -r reports_path; do
            copy_dir=".test-results/$(dirname "$reports_path")"

            echo "Copy $reports_path into $copy_dir"

            mkdir -p "$copy_dir"
            cp -r "$reports_path" "$copy_dir/"
          done < <(find . -name "reports" -d | grep "/reports/")

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: test-reports
          path: ${{ steps.test-reports.outputs.path }}

      - id: test-results
        name: Aggregate test-results into the single directory
        if: always()
        run: |
          echo "path=.test-results" >> $GITHUB_OUTPUT

          mkdir -p .test-results

          while read -r xml_path; do
            copy_dir=".test-results/$(dirname "$xml_path")"

            echo "Copy $xml_path into $copy_dir"

            mkdir -p "$copy_dir"
            cp "$xml_path" "$copy_dir/"
          done < <(find . -name "*.xml" | grep "/test-results/")

      - name: Upload test-results
        if: always()
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: test-results
          path: ${{ steps.test-results.outputs.path }}
