name: UnitTest

on:
  push:
    branches:
      - main
  pull_request:

run-name: "UnitTest by ${{ github.actor }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - uses: ./.github/actions/setup-java

      - name: Run local tests
        run: ./gradlew testDebug --stacktrace

      - id: test-reports
        if: always()
        uses: ./.github/actions/upload-distributed-files
        with:
          copy-to: .test-reports
          name: reports
          name-type: directory
          artifact-name: 'test-reports'

      - id: test-results
        if: always()
        uses: ./.github/actions/upload-distributed-files
        with:
          copy-to: .test-results
          name: "*.xml"
          name-type: file
          grep-by: /test-results/
          artifact-name: 'test-results'