# Run after-hooks of workflow executions. Changes to this workflow file enables only if it's available on the default branch.
#
# Please note that we should not checkout the target code because it contains unverified changes.

name: Workflow Hook

on:
  workflow_run:
    workflows:
      - UnitTest
      - Format
    types:
      - completed

# Disable all permissions. We have to enable required permissions at job-level.
permissions: {}

run-name: ${{ github.event.workflow_run.name }} - ${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}

# Restrict the concurrency on a pair of a repository owner and a branch.
concurrency:
  group: workflow-hook-${{ github.event.workflow_run.head_repository.owner.login }}:${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  # Run every executions of workflows specified in workflow_run#workflows
  # This job will expose an associated pull request if exists.
  linked-pull-request:

    # Run this job only when it's required.
    # Array-literal is not available in Actions so we have to transform a json string into an array.
    if: >
      github.event.workflow_run.conclusion == 'failure' &&
      contains(fromJSON('["Format"]'), github.event.workflow_run.name) ||
      contains(fromJSON('["UnitTest"]'), github.event.workflow_run.name)

    permissions:
      pull-requests: read # for listing pull requests

    timeout-minutes: 2

    outputs:
      pull-request: ${{ steps.linked-pull-request.outputs.entity }} # pull request entity (string)

    runs-on: ubuntu-latest

    steps:
      - id: linked-pull-request
        uses: actions/github-script@060d68304cc19ea84d828af10e34b9c6ca7bdb31
        with:
          script: |
            // Get the latest pull request

            // We have to use different branch format for fork repos.
            // fork repo = <author-repo>:<branch-name>
            // original repo = <branch-name>

            const headBranch = '${{ github.event.workflow_run.head_repository.fork && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch) || github.event.workflow_run.head_branch }}';

            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',

              head: headBranch,

              direction: 'desc',
              sort: 'updated',
              per_page: 1
            });

            if (pulls.length === 0) {
              core.warning('No pull request is found.');
            } else {
              core.setOutput('entity', pulls[0]);
            }

  # Run every executions of Format workflow. (failure only)
  after-Format:
    needs:
      - linked-pull-request

    if: >
      github.event.workflow_run.name == 'Format' &&
      needs.linked-pull-request.outputs.pull-request &&
      fromJSON(needs.linked-pull-request.outputs.pull-request).number

    permissions:
      pull-requests: write # for creating a comment on pull requests

    timeout-minutes: 2

    runs-on: ubuntu-latest

    steps:
      - if: >
          needs.linked-pull-request.outputs.pull-request
        uses: marocchino/sticky-pull-request-comment@ab2e48d202c7f90b66b32abb04df5005a4b29276
        with:
          header: ping-format
          number: ${{ fromJSON(needs.linked-pull-request.outputs.pull-request).number }}
          recreate: true
          message: >
            Hi @${{ github.event.workflow_run.actor.login }}!
            Codes seem to be unformatted. Please run `./gradlew spotlessKotlinApply` to fix this issue.
            Thank you for your contribution.


  # Run every executions of UnitTest workflow. (always)
  after-UnitTest:
    needs:
      - linked-pull-request

    if: >
      github.event.workflow_run.name == 'UnitTest' &&
      needs.linked-pull-request.outputs.pull-request &&
      fromJSON(needs.linked-pull-request.outputs.pull-request).number

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write # for creating a comment on pull requests

    timeout-minutes: 2

    runs-on: ubuntu-latest

    steps:
      - if: >
          needs.linked-pull-request.outputs.pull-request
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          run_id: ${{ github.event.workflow_run.id }}
          pr: ${{ fromJSON(needs.linked-pull-request.outputs.pull-request).number }}
          name: test-results
          path: .test-results
      - uses: EnricoMi/publish-unit-test-result-action@2a18f80469032d699d37add8926c002e334edd06
        with:
          files: |
            .test-results/**/*.xml
